### ISSUE TITLE
No handlers found！！

### ISSUE THREAD

**Issue by Hengwei-Zhao96** [zhijian-liu/torchprofile#12]
Thanks for your good job, but I found some problems:

No handlers found: "aten::group_norm". Skipped.
No handlers found: "aten::floor_divide". Skipped.
No handlers found: "aten::upsample_bilinear2d". Skipped.

**Comment by zhijian-liu** [comment]
I've updated handlers for these operators. Please install the latest version (`v0.0.3`) and verify whether the issue has been resolved. Thanks!

**Comment by Hengwei-Zhao96** [comment]
Thanks! These issues have been resolved.
