### ISSUE TITLE
Negative MACs

### ISSUE THREAD

**Issue by thesiti92** [zhijian-liu/torchprofile#7]
I'm getting an `overflow encountered` error and profile gives me a negative number of MACS. is this a torchprofile issue or an issue with my model?

**Comment by zhijian-liu** [comment]
Could you please provide me with a sample code that can reproduce this error? Thanks!

**Comment by thesiti92** [comment]
`RuntimeWarning: overflow encountered in long_scalars` I get this warning when running 
```
python search.py --dataroot database/night2day 
--restore_G_path logs/pix2pix/night2day/supernet/checkpoints/latest_net_G.pth 
--output_path logs/pix2pix/night2day/supernet/result.pkl 
--ngf 48 --batch_size 32 
--config_set channels-48 
--real_stat_path real_stat/night2day_B.npz
```
from the gan-compression repo. I can send you the model if you would like. Seems like to get results I should convert the numbers to something with arbitrary precision.

**Comment by thesiti92** [comment]
Example terminal output:
![image](https://user-images.githubusercontent.com/15637532/80613812-97cb5e80-89f2-11ea-8cef-4caf7300822c.png)

**Comment by zhijian-liu** [comment]
Hi, I've tried to convert it to float. Could you please try the latest version and see whether this issue has been resolved?

**Comment by thesiti92** [comment]
seems to be ok now. i still get the overflow warning but no longer get negative values.
Thanks!

**Comment by zhijian-liu** [comment]
Hi, I think this might be an issue of `np.prod`. I've tried to switch to `math.prod`. Could you please check the latest version again and see whether this issue has been resolve? Thanks!

**Comment by zhijian-liu** [comment]
@thesiti92, could you please check the latest version again and see whether the overflow warning has been resolved? Thanks

**Comment by thesiti92** [comment]
yeah sorry my project was on hold for a bit. just tested it and it worked fine for the GAN models i have trained. Thanks again, this is a pretty awesome tool!
